# These are supported funding model platforms# 这些是受支持的资助模式平台# 这些是受支持的资助模式平台

githubGitHub：# 请用最多 4 个已启用 GitHub 赞助的用户名替换，例如，[用户名1， 用户名2]: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]GitHub：# 请用最多 4 个已启用 GitHub 赞助的用户名替换，例如，[用户名1， 用户名2]
patreonPatreon：# 请替换为单个 Patreon 用户名: # Replace with a single Patreon usernamePatreon：# 请替换为单个 Patreon 用户名
open_collectiveopen_collective: # 请替换为单个 Open Collective 用户名: # Replace with a single Open Collective usernameopen_collective: # 请替换为单个 Open Collective 用户名
ko_fiko_fi: # 请用一个 Ko-fi 用户名替换此处: # Replace with a single Ko-fi usernameko_fi: # 请用一个 Ko-fi 用户名替换此处
tidelifttidelift：# 请用单个 Tidelift 平台名称/包名称替换，例如，npm/babel: # Replace with a single Tidelift platform-name/package-name e.g., npm/babeltidelift：# 请用单个 Tidelift 平台名称/包名称替换，例如，npm/babel
community_bridge社区桥接：# 请用单个社区桥接项目名称替换，例如 cloud-foundry: # Replace with a single Community Bridge project-name e.g., cloud-foundry社区桥接：# 请用单个社区桥接项目名称替换，例如 cloud-foundry
liberapayLiberapay：# 请用一个 Liberapay 用户名替换: # Replace with a single Liberapay usernameLiberapay：# 请用一个 Liberapay 用户名替换
issuehuntissuehunt：# 请用一个 IssueHunt 用户名替换: # Replace with a single IssueHunt usernameissuehunt：# 请用一个 IssueHunt 用户名替换
lfx_crowdfundinglfx_crowdfunding: # 请用单个 LFX 众筹项目名称替换，例如，cloud-foundry: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundrylfx_crowdfunding: # 请用单个 LFX 众筹项目名称替换，例如，cloud-foundry
polar极地：#   极地 请用单个极地用户名替换: # Replace with a single Polar username极地：# 请用单个极地用户名替换
buy_me_a_coffee买我一杯咖啡：# 请用单个“买我一杯咖啡”用户名替换: # Replace with a single Buy Me a Coffee username买我一杯咖啡：# 请用单个“买我一杯咖啡”用户名替换
thanks_devthanks_dev：# 请用一个 thanks.dev 用户名替换: # Replace with a single thanks.dev usernamethanks_dev：# 请用一个 thanks.dev 用户名替换
custom自定义：#   自定义 用最多 4 个自定义赞助链接替换链接 1', '链接 2']: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']自定义：# 用最多 4 个自定义赞助链接替换链接 1', '链接 2']
